### ISSUE TITLE
Filtering some inputs from fuzz generated values

### ISSUE THREAD

**Issue by AntoineGagne** [elm-explorations/test#136]
Hi, I checked the documentation and I couldn't find a way to filter out values from `Fuzzer`. Is it something that is possible? I am looking for something akin to [`suchThat`](https://hackage.haskell.org/package/QuickCheck-2.14/docs/Test-QuickCheck-Gen.html#v:suchThat) in QuickCheck (Haskell) or [`?SUCHTHAT`](https://proper-testing.github.io/apidocs/) macro in PropEr (Erlang).

Thanks!

**Comment by drathier** [comment]
We decided to not include that because it's too easy to accidentally filter out too many values. It's much better to build a custom Generator/Fuzzer that only generates good values, or to use `map` to turn invalid values into valid ones, e.g. negative numbers can be mapped with `(\x -> x * -1)` to make them valid. If you do want to filter out values yourself, you can do something like this inside your test:
```
if someCondition then
  a |> Expect.equal b
else
  Expect.pass --skip the input
```

**Comment by laurentpayot** [comment]
@AntoineGagne I ended up writing my own `suchAs` based on @drathier answer:

```elm
import Expect exposing (Expectation)

suchAs : (a -> Bool) -> (a -> Expectation) -> a -> Expectation
suchAs filter expect value =
    if filter value then
        expect value
    else
        Expect.pass
```
I use it like so:
```elm
fuzz string "True if non empty string" <| 
    suchAs (not << String.isEmpty) <|
        \randomStr ->   
            myFunction randomStr
            |> Expect.equal True 
```
