### ISSUE TITLE
V2 not published

### ISSUE THREAD

**Issue by stoeffel** [elm-explorations/test#206]
Is it possible that we only bumped the change log and version in the repo, but didn't actually release the new version?

Came here because I read the changelog on node-test-runner https://github.com/rtfeldman/node-test-runner/blob/master/CHANGELOG.md#0191-revision10---2022-10-11

**Comment by Janiczek** [comment]
@stoeffel Do you see some signs of the version not being released?

I've ran the `elm publish` commands and I can use `2.0.1` in my Elm code without a problem.

The package site also lists the two new versions:

![Screenshot 2022-10-13 at 13 53 17](https://user-images.githubusercontent.com/149425/195589282-9b8a1c4e-50e1-4c7c-8f59-0f6078405b2f.png)

![Screenshot 2022-10-13 at 13 53 22](https://user-images.githubusercontent.com/149425/195589302-b5eb1f14-2c3c-4e38-a8b0-3865e7051c07.png)

The `master` branch here has 2.0.1 in elm.json and in the CHANGELOG...

I'm slightly confused what the issue is 😅

**Comment by stoeffel** [comment]
oh weird. I don't see 2.0.0 on the package site
![Screenshot 2022-10-13 at 14 25 13](https://user-images.githubusercontent.com/1217681/195595506-e764f17f-6e3e-46f6-9f22-9c67c15247ad.png)

**Comment by Janiczek** [comment]
https://github.com/elm/package.elm-lang.org/issues/279
