### ISSUE TITLE
Support list shuffling fuzzer

### ISSUE THREAD

**Issue by dasch** [elm-explorations/test#61]
I have a working version of `sortedList : List a -> Fuzz (List a)` that generates versions of a list with different sort ordering; however, it depends on [`Random.List.shuffle`](https://package.elm-lang.org/packages/elm-community/random-extra/latest/Random-List#shuffle) from [`elm-community/random-extra`](https://package.elm-lang.org/packages/elm-community/random-extra/):

```elm
shuffle : List a -> Fuzzer (List a)
shuffle list =
    Fuzz.custom (Random.List.shuffle list) Shrink.noShrink
```

I think it's pretty useful to be able to fuzz test that different sort orderings of a list produce the same outcome, so I'd love to have first class support for it.

**Comment by dasch** [comment]
Maybe `shuffle` is better than `sortedList`.

**Comment by drathier** [comment]
Would it help to add a "remove one element and shuffle the resulting list" branch to the frequency list of the normal list shrinker?

**Comment by mgold** [comment]
I think that's a separate issue. (What bugs would that find?)

**Comment by dasch** [comment]
@mgold wrote
> I sounds like you're able to implement this in terms of exposed primitives and the third party library. Is that correct?

Yup, but I needed a non-core package to do it, and had to use `custom`.

> You should be able to shrink the list-to-shrink down to the list argument, provided they are not equal. I could also imagine a version that takes a `List comparable` and attempts to sort the list as a shrinking strategy.

Looking through the code, it's all very confusing to me. I'm not sure I'd produce a very good implementation.

**Comment by dasch** [comment]
@mgold I would imagine that the best shrink would be the one with the fewest changes from the input list, using something like the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). I'm not sure how the permutations are generated – maybe this is achieved automatically, if successive permutations incrementally change from the input?

**Comment by mgold** [comment]
I was thinking something simpler: if the shuffled list fails, try the unshuffled one. I grant that it's not obvious if you're not familiar with the innards of the library.

**Comment by mgold** [comment]
@dasch Is everything good here? Can this issue be closed?

**Comment by dasch** [comment]
@mgold has the feature been implemented?

**Comment by mgold** [comment]
>> It sounds like you're able to implement this in terms of exposed primitives and the third party library. Is that correct?

>Yup, but I needed a non-core package to do it, and had to use `custom`.

Can you post your implementation as a starting point?

**Comment by dasch** [comment]
Sure. This is using `Random.List.shuffle` from `elm-community/random-extra`.

```elm
shuffle: List a -> Fuzzer (List a)
shuffle list =
    Fuzz.custom (Random.List.shuffle list) Shrink.noShrink
```

**Comment by mgold** [comment]
Thanks. Now let's think about if this would be useful enough to include in the library.

Your use case of parsing arguments is compelling. A valid list of arguments has no repeats (right? Otherwise you could randomly generate a list of them). You may also have constraints about arguments that must or must not be supplied together. That sounds tricky to model in fuzzers.

But, for any (finite) list (of distinguishable elements) there's an exact number of orderings. For small lists it might make sense to try them all. For larger lists, randomly sampling orderings can make sense.

But I'm not sure if this function is useful for a lot of other cases beyond argument parsing, which is kind of a weird one for a front-end language. It's a lot easier to add API than to take it away. I am also concerned that for most cases it's better to fuzz the entire list -- which implicitly means its order -- and for most situations, reordering hard-coded values produces less comprehensive fuzz testing.

**Comment by dasch** [comment]
I fully understand the desire to not take on new API surface area unless there's a broad demand. If this is an esoteric use case I'm fine with the issue being closed.

As for more use cases, I could imagine that it would be valuable to e.g. test that the final state of processing a sequence of events is independent of the order of the events.

**Comment by mgold** [comment]
>  If this is an esoteric use case I'm fine with the issue being closed.

Thanks for understanding.

> test that the final state of processing a sequence of events is independent of the order of the events.

I think that in most cases, the sequence of events will itself be randomly generated, and therefore have random order already. Argument parsing resists random generation for reasons I talked about in my previous post.
